# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalentry',
            name='activityentry_ptr',
        ),
        migrations.RemoveField(
            model_name='skillentry',
            name='activityentry_ptr',
        ),
        migrations.AddField(
            model_name='personalentry',
            name='cventry_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resumebuilder.CVEntry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillentry',
            name='cventry_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resumebuilder.CVEntry'),
            preserve_default=False,
        ),
    ]
