# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 00:59
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0003_auto_20170718_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalentry',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
