# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 01:02
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0004_auto_20170718_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityentry',
            name='location_country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
