# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0005_auto_20170718_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEntryLinkedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element', to='resumebuilder.CVEntry')),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor01', to='resumebuilder.GroupEntryLinkedList')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor01', to='resumebuilder.GroupEntryLinkedList')),
            ],
        ),
    ]
