# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0007_auto_20170725_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupentrylinkedlist',
            name='predecessor',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='predecessor01', to='resumebuilder.GroupEntryLinkedList'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupentrylinkedlist',
            name='successor',
            field=models.ForeignKey(blank=True, default='0', on_delete=django.db.models.deletion.CASCADE, related_name='successor01', to='resumebuilder.GroupEntryLinkedList'),
            preserve_default=False,
        ),
    ]
