# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 01:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0011_cventry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityentry',
            name='date_begin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activityentry',
            name='date_end',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='activityentry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activityentry',
            name='location_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activityentry',
            name='location_country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='educationentry',
            name='diploma_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='educationentry',
            name='school_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hobbyentry',
            name='hobby_institution',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hobbyentry',
            name='hobby_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personalentry',
            name='email_address',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='personalentry',
            name='family_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personalentry',
            name='given_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personalentry',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='skillentry',
            name='skill_level',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='skillentry',
            name='skill_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='company_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='job_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
