# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0013_auto_20170729_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupentrylinkedlist',
            name='cv_entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cv_entry', to='resumebuilder.CVEntry'),
            preserve_default=False,
        ),
    ]
